# Generated by Django 4.2.15 on 2024-08-09 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 20, 55, 38, 737012, tzinfo=datetime.timezone.utc)),
        ),
    ]
