# Generated by Django 4.2.15 on 2024-08-09 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 20, 58, 45, 116135, tzinfo=datetime.timezone.utc)),
        ),
    ]
